// This is a placeholder file
// The actual aws-exports.js file will be generated by Amplify CLI after running 'amplify init'

const awsmobile = {
  // This will be populated by Amplify CLI
};

export default awsmobile;
